"""The one canonical starter workout plan — see spec §1.3.

DEFAULT_PLAN is a literal, verbatim transcription of
`frontend/src/data/workoutPlan.js`'s `PLAN` object (4 days, 22 exercises, in
`CYCLE` order: upper_a, lower_a, upper_b, lower_b). Field names here are
snake_case (DB column names) even though the JS source and the `GET
/api/plan` wire format use camelCase (`repsLow`/`ytUrl`) — the wire-shape
translation happens in `main.py`'s endpoint, not here.

Used by two call sites, both via `main.py`'s `_seed_plan_for_profile` helper:
- the v6->v7 migration's one-time backfill, for any profile with zero
  `plan_days` rows at migration time (today: just the seeded `kapekost`
  profile) — relocating the plan from a JS import to DB rows with nothing
  lost.
- `create_profile`, so a brand-new profile starts with a real, immediately
  usable starter plan rather than an empty one.

`frontend/src/data/workoutPlan.js` is NOT deleted — it stays as the literal
content this was transcribed from (so the transcription is checkable by
diff) and as frontend test fixture data. Do not paraphrase, shorten, or drop
anything here — a transcription slip is a real content regression, not a
style nit.
"""

DEFAULT_PLAN = [
    {
        "day_key": "upper_a",
        "name": "Upper A",
        "tag": "Chest · Back Horizontal · Arms",
        "icon": "upper",
        "exercises": [
            {
                "exercise_id": "bench_press",
                "name": "Bench Press",
                "alt": "or Dumbbell Press",
                "sets": 3,
                "reps_low": 6,
                "reps_high": 10,
                "bodyweight": False,
                "muscles": ["Chest", "Front Delt", "Triceps"],
                "yt_url": "https://www.youtube.com/results?search_query=bench+press+proper+form+jeff+nippard",
                "cues": [
                    "Retract & depress shoulder blades into bench",
                    "Slight arch — feet flat for a stable base",
                    "Elbows ~70° from torso (not fully flared)",
                    "Bar traces slight diagonal to lower chest",
                    "2 sec controlled descent, full ROM",
                ],
            },
            {
                "exercise_id": "bent_row",
                "name": "Bent-over Row",
                "alt": "or Chest-supported Row",
                "sets": 3,
                "reps_low": 8,
                "reps_high": 12,
                "bodyweight": False,
                "muscles": ["Lats", "Rhomboids", "Rear Delt", "Biceps"],
                "yt_url": "https://www.youtube.com/results?search_query=barbell+bent+over+row+form+tutorial",
                "cues": [
                    "Hinge to ~45°, neutral spine throughout",
                    "Drive elbows back — not flared wide",
                    "Squeeze shoulder blades together at top",
                    "Bar stays close to body on the way up",
                    "Control the descent, no jerking",
                ],
            },
            {
                "exercise_id": "ohp",
                "name": "Overhead Press",
                "alt": "Barbell or Dumbbell",
                "sets": 3,
                "reps_low": 8,
                "reps_high": 12,
                "bodyweight": False,
                "muscles": ["Front Delt", "Side Delt", "Triceps"],
                "yt_url": "https://www.youtube.com/results?search_query=overhead+press+form+tutorial+barbell",
                "cues": [
                    "Grip just outside shoulders, full grip",
                    "Bar starts at upper chest / clavicle",
                    "Head moves back slightly as bar passes face",
                    "Full lockout at top, squeeze glutes throughout",
                    "Core braced — no excessive lower back arch",
                ],
            },
            {
                "exercise_id": "lat_pulldown",
                "name": "Lat Pulldown",
                "alt": "or Pull-up",
                "sets": 3,
                "reps_low": 8,
                "reps_high": 12,
                "bodyweight": False,
                "muscles": ["Lats", "Biceps", "Rear Delt"],
                "yt_url": "https://www.youtube.com/results?search_query=lat+pulldown+proper+form+tutorial",
                "cues": [
                    "Depress shoulder blades before pulling",
                    "Pull elbows down and in to pockets",
                    "Slight layback (~10-15°) is fine",
                    "Full stretch at top — don't rush it",
                    "Bar to upper chest, brief squeeze",
                ],
            },
            {
                "exercise_id": "tricep_pushdown",
                "name": "Tricep Pushdown",
                "alt": "Cable rope or bar",
                "sets": 2,
                "reps_low": 10,
                "reps_high": 15,
                "bodyweight": False,
                "muscles": ["Triceps"],
                "yt_url": "https://www.youtube.com/results?search_query=cable+tricep+pushdown+form+rope",
                "cues": [
                    "Elbows pinned tight to sides",
                    "Slight forward hinge at hips",
                    "Full extension at bottom, squeeze",
                    "2 sec slow return — feel the stretch",
                    "Don't let elbows flare or drift forward",
                ],
            },
            {
                "exercise_id": "db_curl",
                "name": "Dumbbell Curl",
                "alt": "Supinating grip",
                "sets": 2,
                "reps_low": 10,
                "reps_high": 15,
                "bodyweight": False,
                "muscles": ["Biceps", "Brachialis"],
                "yt_url": "https://www.youtube.com/results?search_query=dumbbell+bicep+curl+form+tutorial",
                "cues": [
                    "Start neutral (thumbs up), supinate at top",
                    "Elbows stay at sides — no swinging",
                    "Full extension at bottom every rep",
                    "Squeeze bicep hard at the peak",
                    "Slow on the way down — 2-3 sec",
                ],
            },
        ],
    },
    {
        "day_key": "lower_a",
        "name": "Lower A",
        "tag": "Quad · Hamstring · Calves",
        "icon": "lower",
        "exercises": [
            {
                "exercise_id": "back_squat",
                "name": "Back Squat",
                "alt": "High or Low Bar",
                "sets": 3,
                "reps_low": 6,
                "reps_high": 10,
                "bodyweight": False,
                "muscles": ["Quads", "Glutes", "Hamstrings"],
                "yt_url": "https://www.youtube.com/results?search_query=back+squat+form+tutorial+jeff+nippard",
                "cues": [
                    "Feet shoulder-width, toes out ~30°",
                    "Knees track over toes — no caving in",
                    "Chest up, elbows down (high bar) or back (low bar)",
                    "Depth: hip crease below top of knee minimum",
                    "Drive through mid-foot, not heels or toes",
                ],
            },
            {
                "exercise_id": "rdl",
                "name": "Romanian Deadlift",
                "alt": "Barbell or Dumbbell",
                "sets": 3,
                "reps_low": 8,
                "reps_high": 12,
                "bodyweight": False,
                "muscles": ["Hamstrings", "Glutes", "Lower Back"],
                "yt_url": "https://www.youtube.com/results?search_query=romanian+deadlift+rdl+proper+form",
                "cues": [
                    "Hip hinge — push hips BACK, not down",
                    "Soft bend in knees, maintained throughout",
                    "Bar drags close down the shins and thighs",
                    "Feel deep hamstring stretch at the bottom",
                    "Drive hips forward to stand, squeeze glutes",
                ],
            },
            {
                "exercise_id": "leg_press",
                "name": "Leg Press",
                "alt": "Machine",
                "sets": 3,
                "reps_low": 10,
                "reps_high": 15,
                "bodyweight": False,
                "muscles": ["Quads", "Glutes"],
                "yt_url": "https://www.youtube.com/results?search_query=leg+press+proper+form+foot+placement",
                "cues": [
                    "Feet shoulder-width, mid to upper platform",
                    "Full ROM: knees deep to chest at bottom",
                    "Don't lock out knees completely at top",
                    "Lower back stays pressed to pad",
                    "Controlled descent — don't drop the weight",
                ],
            },
            {
                "exercise_id": "leg_curl",
                "name": "Leg Curl",
                "alt": "Lying or Seated",
                "sets": 3,
                "reps_low": 10,
                "reps_high": 15,
                "bodyweight": False,
                "muscles": ["Hamstrings"],
                "yt_url": "https://www.youtube.com/results?search_query=lying+leg+curl+machine+form+tutorial",
                "cues": [
                    "Hips stay flat on pad throughout",
                    "Curl through full range of motion",
                    "Squeeze at peak contraction, brief hold",
                    "2-3 sec controlled return",
                    "No momentum or swinging the hips",
                ],
            },
            {
                "exercise_id": "standing_calf",
                "name": "Standing Calf Raise",
                "alt": "Machine or Smith Bar",
                "sets": 3,
                "reps_low": 12,
                "reps_high": 20,
                "bodyweight": False,
                "muscles": ["Gastrocnemius", "Soleus"],
                "yt_url": "https://www.youtube.com/results?search_query=standing+calf+raise+form+tutorial",
                "cues": [
                    "Full stretch at bottom — heels below platform edge",
                    "Rise onto ball of foot, not the toes",
                    "1-2 sec hold at the top",
                    "Slow controlled descent — calves grow under stretch",
                    "Knees soft, not locked",
                ],
            },
        ],
    },
    {
        "day_key": "upper_b",
        "name": "Upper B",
        "tag": "Upper Chest · Vertical Pull · Shoulders",
        "icon": "upper",
        "exercises": [
            {
                "exercise_id": "incline_press",
                "name": "Incline DB Press",
                "alt": "30-45° bench",
                "sets": 3,
                "reps_low": 8,
                "reps_high": 12,
                "bodyweight": False,
                "muscles": ["Upper Chest", "Front Delt", "Triceps"],
                "yt_url": "https://www.youtube.com/results?search_query=incline+dumbbell+press+form+tutorial",
                "cues": [
                    "30° bench hits more chest than 45°",
                    "DB at chest height, neutral or angled grip",
                    "Press slightly inward at top for chest squeeze",
                    "Full stretch at bottom — feel it in upper chest",
                    "2-3 sec descent, controlled",
                ],
            },
            {
                "exercise_id": "pullup",
                "name": "Pull-up",
                "alt": "Use assisted machine if needed",
                "sets": 3,
                "reps_low": 6,
                "reps_high": 12,
                "bodyweight": True,
                "muscles": ["Lats", "Biceps", "Rear Delt"],
                "yt_url": "https://www.youtube.com/results?search_query=how+to+pull+ups+proper+form+tutorial",
                "cues": [
                    "Dead hang at bottom — full shoulder elevation",
                    "Initiate: depress shoulder blades first",
                    "Pull elbows down to hips, not behind",
                    "Chin clears bar — chest moves toward bar",
                    "Lower fully — no half reps",
                ],
            },
            {
                "exercise_id": "cable_row",
                "name": "Seated Cable Row",
                "alt": "Close or wide grip",
                "sets": 3,
                "reps_low": 10,
                "reps_high": 12,
                "bodyweight": False,
                "muscles": ["Mid Back", "Rhomboids", "Lats", "Biceps"],
                "yt_url": "https://www.youtube.com/results?search_query=seated+cable+row+form+tutorial",
                "cues": [
                    "Sit tall, slight natural lumbar arch",
                    "Drive elbows back — squeeze mid-back at end",
                    "Hold the peak contraction briefly",
                    "Don't lean back excessively with the torso",
                    "Full arm extension on the return",
                ],
            },
            {
                "exercise_id": "lateral_raise",
                "name": "Lateral Raise",
                "alt": "Dumbbell or cable",
                "sets": 3,
                "reps_low": 12,
                "reps_high": 15,
                "bodyweight": False,
                "muscles": ["Side Delt"],
                "yt_url": "https://www.youtube.com/results?search_query=lateral+raise+proper+form+side+delt+tutorial",
                "cues": [
                    "Slight forward lean, slight elbow bend",
                    "Raise to shoulder height — no higher needed",
                    "Lead with elbows, pinky slightly higher than thumb",
                    "No momentum — strict and slow",
                    "Feel the side delt, not traps",
                ],
            },
            {
                "exercise_id": "hammer_curl",
                "name": "Hammer Curl",
                "alt": "Neutral grip DB",
                "sets": 2,
                "reps_low": 10,
                "reps_high": 15,
                "bodyweight": False,
                "muscles": ["Brachialis", "Biceps", "Forearms"],
                "yt_url": "https://www.youtube.com/results?search_query=hammer+curl+form+tutorial+brachialis",
                "cues": [
                    "Neutral grip (thumbs up) throughout the entire rep",
                    "Elbows stay pinned to sides",
                    "Full ROM — full extension at bottom",
                    "Squeeze at peak, no swinging",
                    "Alternating or simultaneous — both effective",
                ],
            },
            {
                "exercise_id": "skull_crusher",
                "name": "Skull Crusher",
                "alt": "EZ bar or dumbbells",
                "sets": 2,
                "reps_low": 10,
                "reps_high": 15,
                "bodyweight": False,
                "muscles": ["Triceps (Long Head)"],
                "yt_url": "https://www.youtube.com/results?search_query=skull+crusher+ez+bar+form+triceps",
                "cues": [
                    "Upper arms vertical, elbows pointed at ceiling",
                    "Lower toward forehead or just behind the head",
                    "Elbows stay stationary — only forearms move",
                    "Full lockout at top, squeeze triceps",
                    "Slow controlled descent",
                ],
            },
        ],
    },
    {
        "day_key": "lower_b",
        "name": "Lower B",
        "tag": "Posterior Chain · Glutes · Power",
        "icon": "lower",
        "exercises": [
            {
                "exercise_id": "deadlift",
                "name": "Deadlift",
                "alt": "Conventional or Trap Bar",
                "sets": 3,
                "reps_low": 4,
                "reps_high": 8,
                "bodyweight": False,
                "muscles": ["Hamstrings", "Glutes", "Spinal Erectors", "Traps"],
                "yt_url": "https://www.youtube.com/results?search_query=alan+thrall+how+to+deadlift+tutorial",
                "cues": [
                    "Bar over mid-foot, hip-width stance",
                    "Grab bar, push shins to bar — don't reach down",
                    '"Protect your armpits" — engage lats hard',
                    "Hips and shoulders rise at the same rate",
                    "Squeeze glutes at lockout, hinge back down",
                ],
            },
            {
                "exercise_id": "bss",
                "name": "Bulgarian Split Squat",
                "alt": "Dumbbells or Barbell",
                "sets": 3,
                "reps_low": 8,
                "reps_high": 12,
                "bodyweight": False,
                "muscles": ["Quads", "Glutes", "Hip Flexors"],
                "yt_url": "https://www.youtube.com/results?search_query=bulgarian+split+squat+form+tutorial",
                "cues": [
                    "Front foot far enough forward — don't tip",
                    "Rear foot on bench, top of foot down",
                    "Slight forward torso lean — engages more glute",
                    "Front knee tracks over toes — no caving",
                    "2 sec descent, explosive drive up",
                ],
            },
            {
                "exercise_id": "hip_thrust",
                "name": "Hip Thrust",
                "alt": "Barbell or machine",
                "sets": 3,
                "reps_low": 10,
                "reps_high": 12,
                "bodyweight": False,
                "muscles": ["Glutes", "Hamstrings"],
                "yt_url": "https://www.youtube.com/results?search_query=barbell+hip+thrust+form+tutorial+glutes",
                "cues": [
                    "Shoulders on bench, bar over hip crease (use a pad)",
                    "Feet flat, shins vertical at the top position",
                    "Drive through heels, squeeze glutes hard at top",
                    "Hips level — no rotation left or right",
                    "Don't hyperextend lower back at top",
                ],
            },
            {
                "exercise_id": "leg_ext",
                "name": "Leg Extension",
                "alt": "Machine",
                "sets": 3,
                "reps_low": 12,
                "reps_high": 15,
                "bodyweight": False,
                "muscles": ["Quads"],
                "yt_url": "https://www.youtube.com/results?search_query=leg+extension+machine+form+tutorial",
                "cues": [
                    "Adjust seat so knee joint aligns with pivot",
                    "Full extension at top — squeeze quads hard",
                    "1-2 sec hold at peak contraction",
                    "Controlled slow descent",
                    "Toes slightly out targets outer quad",
                ],
            },
            {
                "exercise_id": "seated_calf",
                "name": "Seated Calf Raise",
                "alt": "Machine or DB on knees",
                "sets": 3,
                "reps_low": 12,
                "reps_high": 20,
                "bodyweight": False,
                "muscles": ["Soleus", "Gastrocnemius"],
                "yt_url": "https://www.youtube.com/results?search_query=seated+calf+raise+form+soleus+tutorial",
                "cues": [
                    "Knees at 90°, pad on lower thighs",
                    "Full stretch — heels as low as possible",
                    "Rise onto ball of foot, hold 1-2 sec",
                    "Slow controlled descent",
                    "Seated = more soleus activation than standing",
                ],
            },
        ],
    },
]
